name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::786230492177:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Debug files
        run: ls -R

      - name: Sync to S3 (FIXED)
        run: |
          aws s3 sync . s3://cicd-cloud-project-bucket --delete \
          --exclude ".git/*" \
          --exclude ".github/*"